name: check-pr
on: pull_request
jobs:
  generate-asyncapi-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install AsyncAPI Generator
        run: npm install -g @asyncapi/cli
      - name: Generate Organization AsyncAPI UI
        run: asyncapi generate fromTemplate docs/organizations/asyncapi.external.organizations.yaml @asyncapi/html-template@2.3.14 -o docs/organizations/asyncapi.external.organizations
      - name: Commit Organization AsyncAPI changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: alayamarket-ops
          author_email: ops-alayamarket@alayacare.com
          message: 'Re-generated organization async api ui'
          add: 'docs/organizations/asyncapi.external.organizations'
      - name: Generate Offer AsyncAPI UI
        run: asyncapi generate fromTemplate docs/offers/asyncapi.external.offers.yaml @asyncapi/html-template@2.3.14 -o docs/offers/asyncapi.external.offers
      - name: Commit Offer AsyncAPI changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: alayamarket-ops
          author_email: ops-alayamarket@alayacare.com
          message: 'Re-generated offer async api ui'
          add: 'docs/offers/asyncapi.external.offers'
      - name: Auto-merge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "sync"
